---
title: "GSM - AE Distribution Report"
subtitle: "Generated with the Good Statistical Monitoring {gsm} package"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    css: 
      - covariate_styles.css
      - styles.css
params:
  snapshot: NA
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gsm)
library(DT)
library(gt)
library(tidyverse)

library(dplyr)
library(plotly)
library(glue)
library(htmltools)
devtools::load_all()

rpgSelect <- function (inputId, label, choices, selected = NULL, multiple = FALSE, 
          size = NULL) 
{
  selectTag <- shiny::selectInput(inputId, label, choices, 
                                  selected, multiple, selectize = FALSE, width = NULL, 
                                  size)
  selectTag$attribs$class <- NULL
  selectTag$children[[1]]$attribs$class <- NULL
  selectTag$children[[2]] <- selectTag$children[[2]]$children[[1]]
  selectTag$children[[2]]$attribs$class <- if (is.null(size)) {
    "rpgui-dropdown"
  }
  else {
    "rpgui-list"
  }
  selectTag
}

SiteStudyOverlayCharts <- function(dfStudy, dfSite){
  chart_list <- list()
  for(i in unique(dfSite$`Site ID`)){
    # filter site
    site <- dfSite %>%
      filter(`Site ID` == i)
    # overlay site to number plot
    chart_list[['number']][[paste0("site_", i)]] <- ggplotly(
      ggplot() +
        geom_col(data = dfStudy, aes(x = Total, y = reorder(Metric, Total)),
                 alpha = .7, 
                 width = .75, 
                 color = 'blue', 
                 fill = 'dodgerblue') +
        geom_col(data = site, aes(x = `Total Metric`, y = Metric),
                 alpha = .7, 
                 width = .5, 
                 color = 'red', 
                 fill = 'orangered') +
        theme(panel.grid.major.x = element_line(color = "lightgrey", linetype = 4, linewidth = .1),
              panel.grid.minor.x = element_line(color = "lightgrey", linetype = 3, linewidth = .2),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.text.y = element_text(margin = margin(r=5)),
              panel.background = element_rect(fill = "white"),
              panel.grid = element_blank(),
              panel.border = element_rect(color = "lightgrey", fill = NA, linewidth = .25)
        ) +
        scale_x_continuous(limits = c(0,max(dfStudy$Total) + max(dfStudy$Total) * .05), expand = c(0,0)) 
    )
    # overlay site to percent plot
    chart_list[['percent']][[paste0("site_", i)]] <- ggplotly(
      ggplot() +
        geom_col(data = dfStudy, aes(x = Percent, y = "Study Metric", fill = Metric),
                 alpha = .7,  
                 position = "stack") +
        geom_col(data = site, aes(x = Percent, y = "Site Metric", fill = Metric),
                 alpha = .7, 
                 position = "stack") +
        theme(panel.grid.major.x = element_line(color = "lightgrey", linetype = 4, linewidth = .1),
              panel.grid.minor.x = element_line(color = "lightgrey", linetype = 3, linewidth = .2),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.text.y = element_text(margin = margin(r=5)),
              panel.background = element_rect(fill = "white"),
              panel.grid = element_blank(),
              panel.border = element_rect(color = "lightgrey", fill = NA, linewidth = .25),
              legend.position = "none"
        ) +
        scale_x_continuous(limits = c(0,105), expand = c(0,0)),
    )
  }
  return(chart_list)
}
```

```{r}
## Create data --------------------------------------------------------
study_comp <- Covariate_Map(dfCovariate = params$snapshot$lStudyAssessResults$kri0006$lData$dfSTUDCOMP,
              strCovariateColName = "compreas", 
              strWorkflowId = "kri0006"
              )
 
treat_comp <- Covariate_Map(dfCovariate = params$snapshot$lStudyAssessResults$kri0007$lData$dfSDRGCOMP,
              strCovariateColName = "sdrgreas", 
              strWorkflowId = "kri0007"
              )

study_comp_charts <- Covariate_Chart(study_comp)

treat_comp_charts <- Covariate_Chart(treat_comp)

chart_list <- SiteStudyOverlayCharts(study_comp$kri0006$study, study_comp$kri0006$site)
  

```

Study Discontinuation
================================================================

Sidebar {.sidebar}
----------------------------------------------------------------
```{r results='asis'}
# Study
h4(strong("Study:"))
cat(unique(study_comp$kri0006$study$`Study ID`))

# snapshot
h4(strong("Snapshot Date:"))
cat(as.character(params$snapshot$lSnapshotDate))

```

Scatter Plot {.tabset .tabset-fade}
----------------------------------------------------------------
```{r results='asis'}
tab_title("Study-wide Discontinuation Reasons")
```

### <font size=3px>**Scatter Plot**</font> 
```{r}
params$snapshot$lCharts$kri0006$scatterJS
```

### <font size=3px>**Bar Plot (Metric)**</font> 
```{r}
params$snapshot$lCharts$kri0006$barMetricJS
```

### <font size=3px>**Bar Plot (Score)**</font> 
```{r}
params$snapshot$lCharts$kri0006$barScoreJS
```

Bar Plot Study {.tabset .tabset-fade}
----------------------------------------------------------------
```{r results='asis'}
tab_title("Study-wide Discontinuation Reasons")
```

```{r}
fig_bar_study <- round(length(unique(study_comp$kri0006$study$Metric))/1.75)
fig_bar_site <- round(length(unique(study_comp$kri0006$site$`Site ID`))/3)
```


### <font size=3px>**Number**</font> 
```{r fig.height={fig_bar_study} }
opts <- choice <-  as.character(unique(study_comp$kri0006$site$`Site ID`)) # this line replaces last 3 lines
namedChoices = setNames(opts, choice)

newInput <- rpgSelect(         # <----- I'm new; the dropdown
  "selectBox",
  "Site",
  namedChoices,
  multiple = F)

newInput$children[[2]]$attribs$onchange <- "getPlot(this)"

newInput 
```
<div id="plots" style="margin-top:3rem; margin-bottom:3rem;">

```{r dynoPlots,results='asis'}

tagList(chart_list$number) # print every plot (so they're all in the HTML)

```

</div>

```{r giveItUp,results='asis',engine='js'}

/* doesn't catch that the first plot is default, set manually */
setTimeout(function(){
  $('select').select2();                /* connect to the select2 library */
  plt = document.querySelectorAll('div.plotly.html-widget');
  for(i = 0; i < plt.length; i++) {
    if(i === 0) {
      plt[i].style.display = 'block';
    } else {
      plt[i].style.display = 'none';
    }
  }
}, 200) /* run once; allow for loading*/

/* goes with the dropdown; this shows/hides plots based on dropdown */
function getPlot(opt) {
  plt = document.querySelectorAll('div.plotly.html-widget');
  for(i = 0; i < plt.length; i++) {     /* switched to plt from opt here */
    opti = opt.options[i];
    if(opti.selected) {
      plt[i].style.display = 'block';
    } else {
      plt[i].style.display = 'none'
    }
  }
}

```

### <font size=3px>**Percent**</font>

<div id="plots2" style="margin-top:3rem; margin-bottom:3rem;">

```{r results='asis'}

tagList(chart_list$percent) # print every plot (so they're all in the HTML)

```

</div>


Bar Plot Site {.tabset .tabset-fade}
----------------------------------------------------------------
```{r results='asis'}
tab_title("Site-wide Discontinuation Reasons")
```

### <font size=3px>**Number**</font>
```{r fig.height={fig_bar_site} }
study_comp_charts$site_total
```

### <font size=3px>**Percent**</font>
```{r fig.height={fig_bar_site} }
study_comp_charts$site_percent
```

Treatment Discontinuation
================================================================

Sidebar {.sidebar}
----------------------------------------------------------------
```{r results='asis'}
# Study
h4(strong("Study:"))
cat(unique(treat_comp$kri0007$study$`Study ID`))

# Snapshot
h4(strong("Snapshot Date:"))
cat(as.character(params$snapshot$lSnapshotDate))

```

Scatter Plot {.tabset .tabset-fade}
----------------------------------------------------------------
```{r results='asis'}
tab_title("Treatment Discontinuation Rate by Site")
```

### <font size=3px>**Scatter Plot**</font> 
```{r}
params$snapshot$lCharts$kri0007$scatterJS
```

### <font size=3px>**Bar Plot (Metric)**</font> 
```{r}
params$snapshot$lCharts$kri0007$barMetricJS
```

### <font size=3px>**Bar Plot (Score)**</font> 
```{r}
params$snapshot$lCharts$kri0007$barScoreJS
```

Bar Plot Study {.tabset .tabset-fade}
----------------------------------------------------------------
```{r results='asis'}
tab_title("Study-wide Discontinuation Reasons")
```

```{r}
fig_bar_study <- round(length(unique(treat_comp$kri0007$study$Metric))/3)
fig_bar_site <- round(length(unique(treat_comp$kri0007$site$`Site ID`))/3)
```

### <font size=3px>**Number**</font>
```{r fig.height={fig_bar_study} }
treat_comp_charts$study_total
```

### <font size=3px>**Percent**</font>
```{r fig.height={fig_bar_study} }
treat_comp_charts$study_percent
```

Bar Plot Site {.tabset .tabset-fade}
----------------------------------------------------------------
```{r results='asis'}
tab_title("Site-wide Discontinuation Reasons")
```

### <font size=3px>**Number**</font>
```{r fig.height={fig_bar_site} }
treat_comp_charts$site_total
```

### <font size=3px>**Percent**</font>
```{r fig.height={fig_bar_site} }
treat_comp_charts$site_percent
```

```{r echo=FALSE}
covariate <- system.file('utils-0.0.1', 'covariate_test.js', package = "gsm")
```

```{js, file={covariate}, echo=FALSE}
```

