---
title: "GSM - Treatment Discontinuation Deep Dive"
subtitle: "Generated with the Good Statistical Monitoring {gsm} package"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    css: styles.css
params:
    summary: NA
# runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gsm)
library(DT)
library(gt)
library(dplyr)
library(plotly)
library(htmltools)
library(glue)
devtools::load_all("~/Github/gsm.pfs/")
setwd("~/GitHub/gsm/inst/report")
# library(shiny)
```

```{r}
## Create testing data --------------------------------------------------------
# Inputs
dfs = gsm::UseClindata(
  list(
    "dfSUBJ" = "clindata::rawplus_dm",
    "dfSTUDCOMP" = "clindata::rawplus_studcomp",
    "dfSDRGCOMP" = "clindata::rawplus_sdrgcomp %>% filter(.data$phase == 'Blinded Study Drug Completion')"
  )
)
lMapping = gsm::Read_Mapping("rawplus")
strContext = "Study"
bReturnChecks = FALSE
bQuiet = TRUE
strDomain <- ifelse(strContext == "Study", "dfSTUDCOMP", "dfSDRGCOMP")
dfs$dfDISP <- dfs[[strDomain]]
  
# Make testing data
dfDISP <- dfs$dfDISP

dfDISP_mapped <- dfDISP %>% 
  select(
    SubjectID = lMapping[[strDomain]][["strIDCol"]],
    DCReason = lMapping[[strDomain]][[glue::glue("str{strContext}DiscontinuationReasonCol")]],
    Discontinuation = lMapping[[strDomain]][[glue::glue("str{strContext}DiscontinuationFlagCol")]]
  ) %>%
  filter(.data$Discontinuation %in% lMapping[[strDomain]][[glue::glue("str{strContext}DiscontinuationFlagVal")]]) %>%
  mutate(Count = 1)

dfSUBJ_mapped <- dfs$dfSUBJ %>%
  select(
    SubjectID = lMapping[["dfSUBJ"]][["strIDCol"]],
    any_of(
      c(
        SiteID = lMapping[["dfSUBJ"]][["strSiteCol"]],
        StudyID = lMapping[["dfSUBJ"]][["strStudyCol"]],
        CountryID = lMapping[["dfSUBJ"]][["strCountryCol"]],
        CustomGroupID = lMapping[["dfSUBJ"]][["strCustomGroupCol"]]
      )
    )
  )

dfInput <- gsm::MergeSubjects(
  dfDomain = dfDISP_mapped,
  dfSUBJ = dfSUBJ_mapped,
  bQuiet = bQuiet
) %>%
  mutate(
    Count = ifelse(is.na(.data$Count), 0, .data$Count),
    Total = 1
  ) %>%
  group_by(SiteID) %>%
  mutate(Enrolled = n()) %>%
  group_by(SiteID, DCReason) %>%
  mutate(Disc. = n(),
         `%` = pct(round((Disc. / Enrolled) * 100, digits = 2))) %>%
  ungroup() %>%
  filter(!is.na(DCReason)) %>%
  group_by(SubjectID) %>%
  mutate(tot = sample(1:365, 1, replace = TRUE)) %>%
  ungroup() %>%
  select(SiteID,
         SubjectID,
         tot,
         DCReason,
         Enrolled, 
         Disc.,
         `%`)


```

Sidebar {.sidebar}
------------------------------------------------------------------

`r h4(strong("Study:"))`  `r unique(dfs$dfSUBJ$studyid)`

`r h4(strong("Snapshot:"))`  `r Sys.Date()`

### 
```{r}
a <- Disp_Assess(Disp_Map_Raw(), strGroup = "Study")
b <- a$lData$dfSummary$Metric
# 
# renderGauge({
  gauge(b, label = "Study Discontinuation Metric", min = 0, max = 1, abbreviateDecimals = 3, 
        sectors = gaugeSectors(
          success = c(0, .09999),
          warning = c(.1, .24999),
          danger = c(.25, 1))
  )
# })
``` 

```{r}
# # Site selection interactivity
# selectizeInput(inputId = "site_select",
#             label = h4(strong("Site")), 
#             choices = c("All", unique(dfInput$SiteID)),
#             selected = "All",
#             multiple = TRUE,
#             options = list(placeholder = "Select Site"))
# 
# # Discontinuation Filter selection interactivity
# checkboxGroupInput(inputId = "disc_reason_filter", 
#                    label = h4(strong("Disc. Reason Filters")), 
#                    choices = c("All", unique(dfInput$DCReason)),
#                    selected = "All")
# 
# # Time on Treatment range selection interactivity
# sliderInput("treatment_slider",
#             label = h4(strong("Time  on Treatment (days)")),
#             min = 0,
#             max = 365,
#             value = c(0, 365))
# 
# show_df <- reactive({
#   if(any(input$site_select %in% "All")){
#     if(!any(input$disc_reason_filter %in% "All")){
#       dfInput %>%
#         filter(DCReason %in% input$disc_reason_filter) %>%
#         rename("Site" = SiteID,
#                "Subject" = SubjectID,
#                "Time on Treatment" = tot,
#                "Reason for Discontinuation" = DCReason)
#     } else {
#       dfInput %>%
#         rename("Site" = SiteID,
#                "Subject" = SubjectID,
#                "Time on Treatment" = tot,
#                "Reason for Discontinuation" = DCReason)
#     }
#   } else {
#     if(!any(input$disc_reason_filter %in% "All")){
#       dfInput %>%
#         filter(DCReason %in% input$disc_reason_filter,
#                SiteID %in% input$site_select) %>%
#         rename("Site" = SiteID,
#                "Subject" = SubjectID,
#                "Time on Treatment" = tot,
#                "Reason for Discontinuation" = DCReason)
#     } else {
#       dfInput %>%
#         filter(SiteID %in% input$site_select) %>%
#         rename("Site" = SiteID,
#                "Subject" = SubjectID,
#                "Time on Treatment" = tot,
#                "Reason for Discontinuation" = DCReason)
#     }
#   }
# })
# 
# show_df2 <- reactive({
#   show_df() %>%
#     filter(`Time on Treatment` >= input$treatment_slider[1],
#            `Time on Treatment` <= input$treatment_slider[2])
# })

# Ploting
df_disp <- Disp_Map_Raw()
disp_assessment_NormalApprox <- Disp_Assess(df_disp, strMethod = "NormalApprox", bMakeCharts = TRUE)

```            

Scatter Plot
----------------------------------------------------------------
### <font size=5px>**Treatment Discontinuation by Site**</font> 

```{r}
disp_assessment_NormalApprox$lCharts$scatterJS

```

Bar Plot
----------------------------------------------------------------
### <font size=5px>**Study-wide Treatment Discontinuation**</font> 

```{r}
sumry <- pfs_map_summary()
plot_data <- sumry %>%
  group_by(study_comp_reason) %>%
  summarise(Disc. = n()) %>%
  na.omit() 
  # dfInput %>% 
  #          group_by(DCReason) %>% 
  #          summarise(Disc. = sum(Disc.)) %>%
  #          arrange(desc(Disc.))

# txt <- paste0(paste("Discontinuation Reason:", plot$study_comp_reason), "<br>", 
#               paste("Patients Discontinued:", Disc.), "<br>",

ggplotly(
  ggplot(plot_data, aes(x = reorder(study_comp_reason, desc(Disc.)), 
                        y = Disc., 
                        text = paste("Discontinuation Reason:", study_comp_reason))) + #, 
                                 # paste("Patients Discontinued:", Disc.)))) +
    geom_col(fill = "dodgerblue", alpha = .8) +
    geom_text(aes(y = Disc.* 1.05, label = paste(Disc., glue("({pct(round(Disc./nrow(sumry) * 100, digits = 2))} of total patients)")))) +
    xlab("Discontinuation Reason") +
    ylab("# Patients Disc.") +
    expand_limits(y = max(plot_data$Disc.) * 1.1) +
    theme(
      axis.text.x = element_text(angle = 45),
      axis.title.x = element_blank(),
      axis.title.y = element_text(face = "bold", size = 11),
      panel.background = element_rect(fill = "white"),
      panel.grid = element_blank(),
      # panel.grid.major.y = element_line(color = "lightgrey", size = .25),
      # panel.border = ggplot2::element_rect(fill = "NA", color = "darkblue", size = 1.5),
      # axis.line = element_blank()
      axis.line = element_line(color = "lightgrey", size = .25)
    ), tooltip = "text"
  
)
```


valuebox
----------------------------------------------------------------
### Total            
```{r}
# renderValueBox({
#   valueBox(show_df2() %>%
#            nrow(),
#            caption = "Total Patients Matching Criteria",
#            icon = "fa-person")
# })

```

### <font size=5px>**Study Discontinuation Metric**</font>
```{r}
a <- Disp_Assess(Disp_Map_Raw(), strGroup = "Study")
b <- a$lData$dfSummary$Metric
# 
# renderGauge({
  gauge(b, min = 0, max = 1, abbreviateDecimals = 3,
        sectors = gaugeSectors(
          success = c(0, .09999),
          warning = c(.1, .24999),
          danger = c(.25, 1)
        ))
# })
``` 

Table
----------------------------------------------------------------
### <font size=5px>**Treatment Discontinuation Summary**</font> 

```{r}
# renderDT({
  dfInput %>%
    datatable(rownames = FALSE,
              filter = "top")
# })

```

