---
subtitle: "Generated with the Gilead Statistical Monitoring {gsm} package"
date: "Report Generated on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
       collapsed: false
       smooth_scroll: true
    css: styles.css
params:
    assessment: NA
---

```{r, echo=FALSE}
htmltools::img(
  src = knitr::image_uri("gilead.png"), 
  alt = 'logo', 
  style = 'position:absolute; top:0; right:0; padding:10px;', 
  width = "125px", 
  height = "50px"
)
```

---

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(gsm)
library(tidyverse)
library(DT)

assessment <- params$assessment[
  grep("kri", names(params$assessment))
]

overview_table <- Overview_Table(assessment) 

# turn into a function
summary_table <- map(assessment, function(kri) {
  if (kri$bStatus) {
    dfSummary <- kri$lResults$lData$dfSummary
    
    if (nrow(dfSummary) > 0 &
        any(c(-2, -1, 1, 2) %in% unique(dfSummary$Flag))) {
      dfSummary %>%
        filter(Flag != 0) %>%
        arrange(desc(abs(Flag))) %>%
        mutate(FlagDirectionality = map(Flag, kri_directionality_logo),
               across(where(is.numeric),
                      ~ round(.x, 3))) %>%
        DT::datatable()
    } else {
      htmltools::p("Nothing flagged for this KRI.")
    }
    
  } else {
    htmltools::strong("Workflow failed.")
  }
  
})

## StudyID
study_id <- purrr::map(assessment, function(kri) {
    if (kri$bStatus) {
      return(kri$lData$dfInput$StudyID %>% unique())
    } 
  }) %>% 
    discard(is.null) %>% 
    as.character() %>% 
    unique()

```

---
title: "`r study_id` Assessment Overview"
---

## Study Overview

<div class="gsm-overview-table">
```{r echo=FALSE, warning=FALSE}
overview_table
```
</div>


## Select Site
<div class="overall-site-select-container" id="overall-site-select-container">

</div>

## Results

```{r, echo=FALSE, results='asis'}
for (i in seq_along(assessment)) {
  kri_key <- names(assessment)[i]
  kri <- assessment[[ kri_key ]]

  title <- gsm::meta_workflow %>% 
    filter(workflowid == kri_key) %>% 
    pull(metric)

  ### KRI section /
    print(htmltools::h3(title))

    #### charts tabset /
        cat("#### Summary Charts {.tabset} \n")
        
        charts <- assessment[[i]]$lResults$lCharts[
            names(assessment[[i]]$lResults$lCharts) %in% c("scatterJS", "barMetricJS", "barScoreJS")
        ]
        
        for (j in seq_along(charts)) {
            chart_key <- names(charts)[j]
            chart <- charts[[ chart_key ]]
            chart_name <- switch(
            chart_key,
            scatterJS = "Scatter Plot",
            barScoreJS = "Bar Chart (KRI Score)",
            barMetricJS = "Bar Chart (KRI Metric)"
            )

            ##### chart tab /
                chart_header <- paste('#####', chart_name, '\n')

                cat(chart_header)
                
                # need to initialize JS dependencies within loop in order to print correctly
                # see here: https://github.com/rstudio/rmarkdown/issues/1877#issuecomment-678996452
                purrr::map(
                charts,
                ~.x %>%
                    knitr::knit_print() %>%
                    attr('knit_meta') %>%
                    knitr::knit_meta_add() %>%
                    invisible()
                )
            
                # Display chart.
                cat(paste0("<div class =", chart_key, ">"))
                cat(knitr::knit_print(htmltools::tagList(chart)))
                cat("</div>")
            ##### / chart tab
        }
        
        cat("#### {-} \n")
    #### / charts tabset

    #### table /
        if (!is.null(summary_table[[assessment[[i]]$name]])) {
            print(htmltools::h4("Summary Table"))
            print(htmltools::tagList(summary_table[[assessment[[i]]$name]]))
        }
    #### / table
  ### / KRI section
}
```

## Error Log

```{r echo = FALSE}
error <- Study_AssessmentReport(assessment)

error_table <- error$dfSummary %>% 
  arrange(desc(notes), assessment) %>% 
  rename(
    "Assessment" = "assessment",
    "Step" = "step",
    "Check" = "check",
    "Domain" = "domain",
    "Notes" = "notes"
  )

DT::datatable(error_table)
```

```{js echo=FALSE}
function overallSiteDropdown() {
  // add container for drop-down
  const overallSiteSelectContainer = document.getElementById(
    "overall-site-select-container"
  );

  overallSiteSelectContainer.style.position = "relative";
  overallSiteSelectContainer.style.top = 0;
  overallSiteSelectContainer.style.left = 0;

  // add dropdown label
  const overallSiteSelectLabel = document.createElement("span");
  overallSiteSelectLabel.innerHTML = "Select Overall Site ";
  overallSiteSelectContainer.appendChild(overallSiteSelectLabel);

  // add dropdown
  const overallSiteSelect = document.createElement("select");
  overallSiteSelectContainer.appendChild(overallSiteSelect);

  let ids = [...document.querySelector(".site-select").options].map(
    (el) => el.text
  );

  for (id of ids) {
    const siteOptionAll = document.createElement("option");
    siteOptionAll.innerHTML = id;
    overallSiteSelect.appendChild(siteOptionAll);
    overallSiteSelect.classList.add("overall-site-select");
  }
}

document.addEventListener("DOMContentLoaded", function () {
  overallSiteDropdown();

  document
    .querySelector(".overall-site-select")
    .addEventListener("change", function () {
      let canvases = document.querySelectorAll(
        ".scatterJS, .barMetricJS, .barScoreJS"
      );
      canvases = [...canvases].map((el) => el.getElementsByTagName("canvas"));

      let widgets = [];

      canvases.forEach((el) => {
        widgets.push(el[0].chart);
      });

      for (const widget of widgets) {
        widget.data.config.selectedGroupIDs = event.target.value; // site
        widget.helpers.updateConfig(widget, widget.data.config);
        if (event.target.value !== 'None') {
          document.querySelectorAll('.site-select').forEach((el) => el.options[el.selectedIndex].innerHTML = event.target.value)
          document.querySelectorAll('.site-select').forEach((el) => el.disabled = true)
        } else {
          document.querySelectorAll('.site-select').forEach((el) => el.options[el.selectedIndex].innerHTML = 'None')
          document.querySelectorAll('.site-select').forEach((el) => el.disabled = false)
        }
      }
    });
});


```
