---
subtitle: "Generated with the Good Statistical Monitoring {gsm} package"
output:
  html_document:
    toc: true
    toc_float:
       collapsed: false
       smooth_scroll: true
    css: styles.css
params:
    assessment: NA
    status_study: NULL
    status_site: NULL
    status_snap: NULL
    longitudinal: NULL
---

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(gsm)
library(DT)

# Study_Assess() output - QTL metrics only
assessment <- params$assessment[
  grep("qtl", names(params$assessment), ignore.case = TRUE)]


## StudyID
study_id <- purrr::map(assessment, function(kri) {
    if (kri$bStatus) {
      return(kri$lData$dfInput$StudyID %>% unique())
    } 
  }) %>% 
    discard(is.null) %>% 
    as.character() %>% 
    unique()

```

---
title: "`r study_id` Assessment Overview"
---

<div class = 'overall-country-select'
    id = 'overall-country-select'
    title = 'Selected country will be highlighted in all charts for all KRIs.'>

</div>

```{r, echo=FALSE, results='asis'}
## metadata report if longitudinal data is provided
status_study_exists <- exists('status_study', where = params) && !is.null(params$status_study)
if (status_study_exists) {
  subjects <- params$status_study[["enrolled_participants_ctms"]]
  if ("gsm_analysis_date" %in% names(params$status_study))
    snapshot_date <- params$status_study$gsm_analysis_date
  else
    snapshot_date <- Sys.Date()

  glue::glue(
  '
  ---
  date: "Snapshot Date: {snapshot_date}"
  ---
  ') 
}
```

```{r, echo=FALSE, results='asis', eval=status_study_exists}
MakeStudyStatusTable(params$status_study)
Make_Timeline(params$status_study)
```

## Analysis Results

```{r, echo=FALSE, message=FALSE, warning=FALSE}
results_summary <- purrr::imap_dfr(assessment, function(data, index) {
  data$lResults$lData$dfSummary %>% 
    mutate(
      workflowid = index
    ) %>% 
    select(
      workflowid, everything()
      )
})

#combine qtl lData$dfAnalyzed
results_analysis <- purrr::imap_dfr(assessment, function(data, index) {
  data$lResults$lData$dfAnalyzed %>% 
    mutate(
      workflowid = index
    ) %>% 
    select(
      workflowid, everything()
      )
}) %>%
  left_join(results_summary) %>%
  select(-GroupID)

results_analysis[sapply(results_analysis, is.numeric)] <- round(results_analysis[sapply(results_analysis, is.numeric)], digits = 2)

DT::datatable(results_analysis)

```


```{r echo=FALSE, results='asis', eval=!is.null(params$longitudinal)}
summary_table <- MakeSummaryTable(assessment, dfSite = params$status_site)
MakeResultsTable(assessment, summary_table)
```


`r if(!is.null(params$longitudinal)){"## History {.tabset}"}`

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis', eval=!is.null(params$longitudinal)}
history <- params$longitudinal$results_analysis %>% 
    tidyr::pivot_wider(names_from = param,
                       values_from = value) %>%
    left_join(params$longitudinal$results_summary %>%
                select(workflowid, snapshot_date, flag)) %>%
    select(-studyid, -gsm_analysis_date) %>%
    split(., .$workflowid) %>%
    map(., ~select(., -workflowid))

for (i in names(history)){
  cat(glue("### {i}",  "\n"))
  cat("\n")
  print(kable(history[[i]])) 
  cat("\n")
}


```

## QTL Glossary

```{r, echo = FALSE}
MakeKRIGlossary(
  strWorkflowIDs = names(assessment),
  lStatus = params$status_snap
)
```


