---
subtitle: "Generated with the Good Statistical Monitoring {gsm} package"
output:
  html_document:
    toc: true
    toc_float:
       collapsed: false
       smooth_scroll: true
    css: styles.css
params:
    assessment: NA
    status_study: NULL
    status_site: NULL
    status_snap: NULL
    longitudinal: NULL
---

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(gsm)
library(tidyverse)
library(DT)

# Study_Assess() output - country metrics only
assessment <- AssessStatus(params$assessment, strType = "cou")
active <- if("active" %in% names(assessment)) {assessment$active} else {assessment}
dropped <- if("dropped" %in% names(assessment)) {assessment$dropped} else {NULL}

# Overview Table - HTML object
overview_table <- Overview_Table(
  lAssessments = active, 
  dfSite = params$status_site,
  strReportType = "country"
)

# Overview Table - data.frame/raw data
overview_raw_table <- Overview_Table(
  lAssessments = active, 
  dfSite = params$status_site,
  strReportType = "country",
  bInteractive = FALSE
)

red_kris <- overview_raw_table %>% pull(`Red KRIs`) %>% sum()
amber_kris <- overview_raw_table %>% pull(`Amber KRIs`) %>% sum()

# Generate listing of flagged KRIs.
summary_table <- MakeSummaryTable(
 active
)

if(!is.null(dropped)){
  dropped_summary_table <- MakeSummaryTable(
    dropped
  )
}

## StudyID
study_id <- purrr::map(active, function(kri) {
    if (kri$bStatus) {
      return(kri$lData$dfInput$StudyID %>% unique())
    } 
  }) %>% 
    discard(is.null) %>% 
    as.character() %>% 
    unique()

```

---
title: "`r study_id` Assessment Overview"
---

<div class = 'overall-country-select'
    id = 'overall-country-select'
    title = 'Selected country will be highlighted in all charts for all KRIs.'>

</div>

```{r, echo=FALSE, results='asis'}
## metadata report if longitudinal data is provided
status_study_exists <- exists('status_study', where = params) && !is.null(params$status_study)
if (status_study_exists) {
  subjects <- params$status_study[["enrolled_participants_ctms"]]
  if ("gsm_analysis_date" %in% names(params$status_study))
    snapshot_date <- params$status_study$gsm_analysis_date
  else
    snapshot_date <- Sys.Date()

  glue::glue(
  '
  ---
  date: "Snapshot Date: {snapshot_date}"
  ---
  ') 

}
```

```{r, echo=FALSE, results='asis', eval=status_study_exists}
MakeStudyStatusTable(params$status_study)
Make_Timeline(params$status_study)
```

## Study Overview

<div class="flag-container">
  <div class="flag flag-red">`r red_kris` Red KRIs</div>
  <div class="flag flag-amber">`r amber_kris` Amber KRIs</div>
</div>


<div class="gsm-overview-table">
```{r echo=FALSE, warning=FALSE}
overview_table
```
</div>

```{r, echo=FALSE, results = 'asis', warning=TRUE, eval = status_study_exists}
cat(glue::glue("As of {snapshot_date}, {study_id} has {subjects} participants enrolled across 
{length(unique(overview_raw_table$Country))} countries. {red_kris} Country-KRI combinations have been flagged as red across {overview_raw_table %>% filter(.data$`Red KRIs` != 0) %>% nrow()} countries as shown in the Study Overview Table above\n
  - {overview_raw_table %>% filter(.data$`Red KRIs` != 0) %>% nrow()} countries have at least one red KRI\n
  - {overview_raw_table %>% filter(.data$`Red KRIs` != 0 | .data$`Amber KRIs` != 0) %>% nrow()} countries have at least one red or amber KRI\n
  - {overview_raw_table %>% filter(.data$`Red KRIs` == 0 & .data$`Amber KRIs` == 0) %>% nrow()} countries have neither red nor amber KRIs and are not shown"), sep = "\n")
```

## Results

```{r, echo=FALSE, results='asis'}
MakeResultsTable(
  active,
  summary_table
)
```


## KRI Glossary

```{r echo = FALSE}
MakeKRIGlossary(
  strWorkflowIDs = names(active),
  lStatus = params$status_snap
)
```


## Error Log

```{r echo = FALSE}
error <- Study_AssessmentReport(active)

error_table <- error$dfSummary %>% 
  arrange(desc(notes), assessment) %>% 
  rename(
    "Assessment" = "assessment",
    "Step" = "step",
    "Check" = "check",
    "Domain" = "domain",
    "Notes" = "notes"
  )

DT::datatable(error_table)
```

`r if(!is.null(dropped)){"## Inactive KRI's"}`

```{r, echo=FALSE, results='asis', eval=!is.null(dropped)}
MakeResultsTable(dropped,
                 dropped_summary_table)
if(length(dropped) == 0){
  cat("No Inactive KRI's")
}
```

```{js, file='../utils-0.0.1/overallSiteDropdown.js', echo=FALSE}
```

```{js, file='../utils-0.0.1/dragOverallSiteDropdown.js', echo=FALSE}
```

```{js, file='../utils-0.0.1/showMetaTableDetails.js', echo=FALSE}
```
