---
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    css: styles.css
params:
  lCharts: NA
  dfResults: NA
  dfGroups: NA
  dfMetrics: NA
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(gsm)
library(gt)

setup <- Report_Setup(
  dfGroups =  params$dfGroups, 
  dfMetrics = params$dfMetrics, 
  dfResults = params$dfResults
)

```
---
title: "`r setup$GroupLevel` KRI Overview"
subtitle: "Study: `r setup$StudyLabel`"
date: "Snapshot Date: `r setup$SnapshotDate`"
--- 

::: {
    #overall-group-select
    .overall-group-select
    title="Selected group will be highlighted in all charts for all KRIs."
}
:::

```{r, echo=FALSE, results='asis', fig.height=2}
Report_StudyInfo(params$dfGroups)
```

## Study Overview

::: flag-container
::: {.flag .flag-red}
<div> `r setup$red_kris` Red KRIs </div>
:::

::: {.flag .flag-amber}
<div> `r setup$amber_kris` Amber KRIs </div>
:::
:::

::: gsm-overview-table


```{r echo=FALSE, warning=FALSE, results = 'asis'}
if(setup$GroupLevel == "Site"){ 
  GroupLabelKey <- "InvestigatorLastName"
} else { 
  GroupLabelKey <- NULL 
}  

# subset data on latest snapshot date
dfResults_current <- FilterByLatestSnapshotDate(params$dfResults)

GroupOverViz <- Widget_GroupOverview(
  dfResults = dfResults_current,
  dfGroups = params$dfGroups,
  dfMetrics = params$dfMetrics,
  strGroupLevel = setup$GroupLevel,
  strGroupSubset = switch(setup$GroupLevel,
    "Site" = "red",
    "Country" = "all",
    "Study" = "all"
  ),
  strGroupLabelKey = GroupLabelKey
)

overview_viz <- list(groupOverview = GroupOverViz)

# Add FlagOverTime Table if data has more than one snapshot
if(length(unique((params$dfResults)$SnapshotDate)) > 1){
  intSnapshots <- 12L # consider adding this as a parameter
  strSnapshotDates <- unique(params$dfResults$SnapshotDate) %>%
    sort(decreasing = TRUE) %>%
    head(intSnapshots)

  # Only include risk signals flagged at the most recent snapshot and the 12 most recent snapshots.
  dfResultsFlagged <- params$dfResults %>%
    FilterByFlags(bCurrentlyFlagged = TRUE) %>%
    dplyr::filter(
      .data$SnapshotDate %in% strSnapshotDates
    )

  overview_viz$flagOverTime <- Widget_FlagOverTime(
    dfResults = dfResultsFlagged,
    dfMetrics = params$dfMetrics,
    strGroupLevel = setup$GroupLevel,
    strFootnote = glue::glue(
      "Table displays the {
        length(strSnapshotDates)
      } most recent snapshots and only includes risk signals flagged in the most recent snapshot."
    ),
    bExcludeEver = TRUE
  )
}

Report_MetricCharts(overview_viz, overview = TRUE)
```

:::

```{r, echo=FALSE, results = 'asis'}

Report_OverviewText(
  lSetup = setup,
  dfResults = dfResults_current,
  lStudy = setup$lStudy
)


```

## Results

```{r, echo=FALSE, results='asis'}

for (i in unique(params$dfResults$MetricID)) {
  lMetric <- params$dfMetrics %>% dplyr::filter(MetricID == i) %>% as.list

  print(htmltools::h3(lMetric$Metric))
  
  Report_MetricCharts(
    lCharts = params$lCharts[[lMetric$MetricID]],
    strMetricID = lMetric$MetricID,
    overview = FALSE
  )
  
  print(htmltools::tags$br())

}

```

## Metric Details
```{r, echo=FALSE, results='asis'}
#print dfMetrics table
params$dfMetrics %>%
  gt::gt()

```

```{r echo=FALSE}
group_dropdown <- system.file('report', 'lib', 'overallGroupDropdown.js', package = "gsm")
dropdown_drag <- system.file('report', 'lib', 'dragOverallGroupDropdown.js', package = "gsm")
```

```{js, file={group_dropdown}, echo=FALSE}
```

```{js, file={dropdown_drag}, echo=FALSE}
```

```{js}
document.addEventListener("DOMContentLoaded", function () {
  console.log("Document loaded. Initializing TOC toggle functionality.");
 
  // Create the toggle button
  const button = document.createElement("div");
  button.id = "toc-toggle";
  button.style.position = "fixed";
  button.style.top = "10px";
  button.style.left = "10px";
  button.style.zIndex = "1000";
  button.style.width = "40px";
  button.style.height = "25px";
  button.style.display = "flex";
  button.style.flexDirection = "column";
  button.style.justifyContent = "space-around";
  button.style.alignItems = "center";
  button.style.backgroundColor = "transparent";
  button.style.border = "none";
  button.style.cursor = "pointer";
 
  // Create the hamburger lines
  for (let i = 0; i < 3; i++) {
    const line = document.createElement("div");
    line.style.width = "100%";
    line.style.height = "4px";
    line.style.backgroundColor = "gray";
    line.style.borderRadius = "2px";
    button.appendChild(line);
  }
 
  document.body.appendChild(button);
  console.log("Hamburger toggle button created and added to the page.");
 
  // Select the TOC and main content elements
  const toc = document.querySelector("#TOC");
  const mainContent = document.querySelector(".col-xs-12.col-sm-8.col-md-9");
 
  // Add click event to toggle TOC visibility and adjust content width
  button.addEventListener("click", function () {
    console.log("Toggle button clicked.");
    toc.classList.toggle("hidden");
 
    if (toc.classList.contains("hidden")) {
      console.log("TOC is now hidden. Expanding main content.");
      mainContent.classList.remove("col-sm-8", "col-md-9");
      mainContent.classList.add("col-sm-12", "col-md-12");
    } else {
      console.log("TOC is now visible. Restoring main content width.");
      mainContent.classList.remove("col-sm-12", "col-md-12");
      mainContent.classList.add("col-sm-8", "col-md-9");
    }
  });
 
  // Add CSS for the 'hidden' class dynamically
  const style = document.createElement("style");
  style.innerHTML = `
    #TOC.hidden {
      display: none;
    }
  `;
  document.head.appendChild(style);
});
 
```
