---
title: "Assessment Overview for `r params$meta$Project`"
subtitle: "Generated with the Gilead Statistical Monitoring {gsm} package"
author: 
    - George Wu
    - Jeremy Wildfire
output:
  html_document:
     toc: true
     theme: united
params:
    assessments: NA
    meta: NA 
---

```{r, results='asis', echo = FALSE, message=FALSE, warning = FALSE}
library(gsm)
library(tidyverse)
library(kableExtra)
library(gt)

if (length(names(params$meta)) > 1) {
  cat("# Metadata Table")
  params$meta %>%
    tibble::enframe() %>%
    tidyr::unnest(cols = value) %>%
    dplyr::rename(Name = name, Value = value) %>%
    gt::gt() %>%
    gt::tab_style(
      style = list(
        cell_text(
          color = "white",
          align = "center",
          weight = "bold"
        ),
        cell_fill(color = "#c73442")
      ),
      locations = cells_column_labels()
    )
}
```

# Overview Table
```{r, results='asis', echo = FALSE, message=FALSE, warning = FALSE}
results <- params$assessments %>%
    purrr::map(~ .x$lResults) %>%
    purrr::discard(is.null) %>%
    purrr::compact() 
    
allFindings <- results %>%
  purrr::map_df(~ .x$lData$dfSummary, .id = 'Assessment')
table <- gsm::Study_Table(allFindings)

overview_tbl <- table$df_summary %>%
  mutate(across(everything(), ~ map(., ~ gt::html(.)))) %>%
  gt::gt() %>%
  gt::tab_style(
    style = list(
      cell_text(color = "white", align = "left", weight = "bold"),
      cell_fill(color = "#50504f")
    ),
    locations = cells_body(columns = 1)
  ) %>%
  gt::tab_style(
    style = list(
      cell_text(color = "white", align = "center", weight = "bold"),
      cell_fill(color = "#c73442")
    ),
    locations = cells_column_labels()
  ) %>%
  gt::tab_style(
    style = list(
      cell_fill(color = "#f8f9fa")
    ),
    locations = cells_body(columns = -Title, rows = 1:2)
  )

if (!is.null(table$footnote)) {
  overview_tbl %>%
    gt::tab_footnote(
      footnote = table$footnote,
      locations = cells_column_labels(
        columns = Title
      )
    )
} else {
  overview_tbl
}
```

```{js, class.source = "jsvis1", echo=FALSE}
function showDetails(elem){
    console.log(elem.textContent)
    if(elem.textContent.trim()=="Show details"){
        console.log("showing")
        elem.parentNode.getElementsByClassName('detail-wrap')[0].style.display=null
        elem.textContent="Hide details"
    }else{
        console.log("hiding")
        elem.parentNode.getElementsByClassName('detail-wrap')[0].style.display="none"
        elem.textContent="Show details"
    }
}
```

# Results
```{r, echo=FALSE, results='asis'}

for (i in seq_along(results)) {
  result <- results[[i]]
  title <- gsm::meta_workflow %>%
    filter(workflowid == names(params$assessments)[i]) %>%
    pull(metric)


  # title
  cat(paste0('\n\n## ', title, '\n\n'))

  
  # chart
  if (!is.null(result$lCharts$barScore) |
      !is.null(result$lCharts$scatter)  |
      !is.null(result$lCharts$barMetric)) {
  cat("<h3>Summary Charts</h3>")
  cat("<div style = 'text-align: center'>")
  print(result$lCharts$barScore)
  cat("</div>")
  cat("<div style = 'text-align: center'>")
  print(result$lCharts$scatter)
  cat("</div>")
  cat("<div style = 'text-align: center'>")
  print(result$lCharts$barMetric)
  cat("</div>")
    
  }


  # table
  cat("<h3>Flagged Sites</h3>")

  
  flagged <- result$lData$dfSummary %>%
    filter(Flag != 0)

  if (nrow(flagged) > 0) {
    flagged %>%
      kbl(escape = FALSE) %>%
      kable_styling() %>%
      cat()
  }

  cat(
    paste0(
      "<p>",
      length(unique(flagged$GroupID)),
      " of ",
      length(unique(result$lData$dfSummary$GroupID)),
      " sites flagged for this assessment.",
      "</p>"
    )
  )

  details <- result$lData$dfFlagged %>%
    filter(Flag != 0) %>%
    arrange(., match(GroupID, flagged$GroupID))

  if (length(unique(flagged$GroupID)) > 0) {
    cat("<div><button onclick='showDetails(this)'>Show details</button>")
    cat("<div class='detail-wrap' style='display:none'>")

    cat("<h3>Model Details</h3>")
    
      if (nrow(details) > 0) {
        details %>%
          kbl(escape = FALSE) %>%
          kable_styling() %>%
          cat()
      }
    
    cat("</div>")
    cat("</div>")
    
  }



}
```

# Appendix - Data Check Summary

## Assessment Checks
```{r, echo = FALSE, message=FALSE, warning = FALSE}
with_tooltip <- function(value, tooltip) {
  htmltools::tags$abbr(
    style = "text-decoration: underline; text-decoration-style: solid; cursor: question; color: blue",
    title = tooltip, value
  )
}
AssessmentReport <- gsm::Study_AssessmentReport(params$assessments)
AssessmentReport$dfSummary %>%
  gt::gt() %>%
  gt::tab_style(
    style = list(
      cell_text(color = "white", align = "center", weight = "bold"),
      cell_fill(color = "#c73442")
    ),
    locations = cells_column_labels()
  ) %>%
  gt::fmt_markdown(columns = everything())
```

## Issue List
```{r, results='asis', echo = FALSE, message=FALSE, warning = FALSE}
assessment_report <- AssessmentReport$dfAllChecks %>%
  filter(check > 1) %>%
  mutate(
    check = map(check, rank_chg),
    across(where(is.character), ~ replace_na(., ""))
  )

if (nrow(assessment_report) > 0) {
    gt::gt() %>%
  gt::tab_style(
    style = list(
      cell_text(color = "white", align = "center", weight = "bold"),
      cell_fill(color = "#c73442")
    ),
    locations = cells_column_labels()
  ) %>%
  gt::cols_width(
    assessment ~ px(85),
    step ~ px(140),
    check ~ px(60),
    domain ~ px(100),
    notes ~ px(300),
    everything() ~ px(200)
  ) %>%
  gt::fmt_markdown(columns = everything())
} else {
  cat("<div style = 'text-align: center'>")
  cat("<p>No issues for this workflow!</p>")
  cat("</div>")
}

```



