---
title: "GSM - AE Distribution Report"
subtitle: "Generated with the Good Statistical Monitoring {gsm} package"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    css: styles.css
params:
  snapshot: NA
  meta_workflow: NA
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gsm)
library(DT)
library(gt)
library(dplyr)
library(plotly)
library(glue)
library(htmltools)
devtools::load_all()
```

```{r}
snapshot <- Make_Snapshot()
dist_list <- list(
  kri0001 = c("dfAE", "mdrsoc_nsv"),
  kri0002 = c("dfAE", "mdrsoc_nsv"),
  kri0003 = c("dfPD", "companycategory"),
  kri0004 = c("dfPD", "companycategory"),
  kri0005 = c("dfLB", "lbtstnam"),
  kri0006 = c("dfSTUDCOMP", "compreas"),
  kri0007 = c("dfSDRGCOMP", "sdrgreas"),
  #kri0008 = params$snapshot$lInputs$lData$dfAE, #?
  kri0009 = c("dfQUERY", "formoid"),
  kri0010 = c("dfDATAENT", "formoid"),
  kri0011 = c("dfDATACHG", "formoid"),
  kri0012 = c("dfENROLL", "sfreas")
)

lInput <- Distribution_Map(snapshot, dist_list)
plots <- Distribution_Charts(lInput)

create_sidebar <- function(study, date, total){
  # Study
  print(h4(strong("Study:")))
  cat(study)
  
  # Snapshot
  print(h4(strong("Snapshot:")))
  cat(date)
  
  # # Total Patients
  print(h4(strong("Total Patients:")))
  cat(total)
}

Process_Distribution_Page <- function(lSnapshot, dfInput, Plot, kri){
    # Create Page title ----------------------------------------------------
    page_title <- lSnapshot$lInputs$lMeta$meta_workflow %>%
      filter(workflowid == kri) %>%
      pull(abbreviation)
    
    # Create Page ----------------------------------------------------------
    cat(paste0(kri, "-" , page_title), "\n")
    cat("================================================================\n")
      
    # Create Page Sidebar --------------------------------------------------
    cat("Sidebar {.sidebar}\n")
    cat("----------------------------------------------------------------\n")
    
    create_sidebar(study = unique(lInput$kri0001$study$`Study ID`),
                   date = as.character(snapshot$lSnapshotDate),
                   total = unique(lInput$kri0001$study$Enrolled))
    
    # Create KRI JS plots Section -------------------------------------------
    cat("\n\n Scatter Plot {.tabset .tabset-fade} \n")
    cat("----------------------------------------------------------------\n")
    
    ## Create KRI JS plots section title
    tab_title("Treatment Discontinuation by Site")
    
    ## Create Scatter JS plot
    cat("### <font size=3px>**Scatter Plot**</font>", "\n")
    snapshot$lCharts$kri0001$scatterJS %>%
      knitr::knit_print() %>%
      attr("knit_meta") %>%
      knitr::knit_meta_add() %>%
      invisible()
    
    ## Create Bar Metric JS plot
    cat("### <font size=3px>**Bar Plot (Metric)**</font>", "\n") 
    snapshot$lCharts$kri0001$barMetricJS %>%
      knitr::knit_print() %>%
      attr("knit_meta") %>%
      knitr::knit_meta_add() %>%
      invisible()
    
    ## Create Bar Score JS plot
    cat("### <font size=3px>**Bar Plot (Score)**</font>", "\n")
    snapshot$lCharts$kri0001$barScoreJS %>%
      knitr::knit_print() %>%
      attr("knit_meta") %>%
      knitr::knit_meta_add() 
    
    # Create Study Bar Plot Section -----------------------------------------
    cat("\n")
    cat("Bar Plot Study", "\n")
    cat("----------------------------------------------------------------\n")
    
    ## Specify figure height
    # fig_bar_study <- round(length(unique(lInput$kri0001$study$Metric))/3)
    # fig_bar_site <- round(length(unique(lInput$kri0001$site$`Site ID`))/3)
    
    ## Make Title
    cat("### <font size=5px>**Study-wide Metrics**</font>", "\n") 
    ## Make Plot
    plots$kri0001$study %>%
      knitr::knit_print() %>%
      attr("knit_meta") %>%
      knitr::knit_meta_add()
    
    # Create Site Bar Plot Section ------------------------------------------
    cat("\n")
    cat("Bar Plot Site", "\n")
    cat("----------------------------------------------------------------\n")
    ## Make Title
    cat("### <font size=5px>**Site-wide Metrics**</font>", "\n") 
    plots$kri0001$site %>%
      knitr::knit_print() %>%
      attr("knit_meta") %>%
      knitr::knit_meta_add() 
    
    # Create Site Bar Plot Section ------------------------------------------
    cat("\n")
    cat("Table", "\n")
    cat("----------------------------------------------------------------\n")
    ## Make Title  
    cat("### <font size=5px>**AE Reasons Summary**</font>", "\n") 
    lInput$kri0001$site %>%
      datatable(rownames = FALSE)
}
```


```{r results='asis'}
Process_Distribution_Page(snapshot, lInput$kri0001, plots$kri0001, "kri0001")
```
