db:
  clindata: "clindata"
  local: "./data"
  s3: "s3://AA-AA-000-0000/data"
schemas:
  Raw:
    db:
      clindata: "clindata"
      #local: "./data/{SnapshotDate}/Raw/{ID}.csv"
      #s3: "s3://AA-AA-000-0000/data/{SnapshotDate}/Raw/{ID}.parquet"
    domains:
      Raw_STUDY:
        db: clindata
        table: ctms_study
      Raw_SITE:
        db: clindata
        table: ctms_site
      Raw_SUBJ:
        db: clindata
        table: rawplus_dm
      Raw_ENROLL:
        db: clindata
        table: rawplus_enroll
      Raw_STUDCOMP:
        db: clindata
        table: rawplus_studcomp
      Raw_SDRGCOMP:
        db: clindata
        table: rawplus_sdrgcomp
      Raw_AE:
        db: clindata
        table: rawplus_ae
      Raw_LB:
        db: clindata
        table: rawplus_lb
      Raw_PD:
        db: clindata
        table: ctms_protdev
      Raw_DATAENT:
        db: clindata
        table: edc_data_pages
      Raw_DATACHG:
        db: clindata
        table: edc_data_points
      Raw_QUERY:
        db: clindata
        table: edc_queries
  Mapped:
    db:
      local: "./data/{SnapshotDate}/Mapped/{ID}.csv"
      s3: "s3://AA-AA-000-0000/data/{SnapshotDate}/Mapped/{ID}.parquet"
    domains:
      Mapped_STUDY:
        db: local
        table: "./data/{SnapshotDate}/Mapped/STUDY.csv"
      Mapped_SITE:
        db: local
        table: "./data/{SnapshotDate}/Mapped/SITE.csv"
      Mapped_COUNTRY:
        db: local
        table: "./data/{SnapshotDate}/Mapped/COUNTRY.csv"
      Mapped_SUBJ:
        db: local
        table: "./data/{SnapshotDate}/Mapped/SUBJ.csv"
      Mapped_ENROLL:
        db: local
        table: "./data/{SnapshotDate}/Mapped/ENROLL.csv"
      Mapped_STUDCOMP:
        db: local
        table: "./data/{SnapshotDate}/Mapped/STUDCOMP.csv"
      Mapped_SDRGCOMP:
        db: local
        table: "./data/{SnapshotDate}/Mapped/SDRGCOMP.csv"
      Mapped_AE:
        db: local
        table: "./data/{SnapshotDate}/Mapped/AE.csv"
      Mapped_LB:
        db: local
        table: "./data/{SnapshotDate}/Mapped/LB.csv"
      Mapped_PD:
        db: local
        table: "./data/{SnapshotDate}/Mapped/PD.csv"
      Mapped_DATAENT:
        db: local
        table: "./data/{SnapshotDate}/Mapped/DATAENT.csv"
      Mapped_DATACHG:
        db: local
        table: "./data/{SnapshotDate}/Mapped/DATACHG.csv"
      Mapped_QUERY:
        db: local
        table: "./data/{SnapshotDate}/Mapped/QUERY.csv"
  Analysis:
    db:
      local: "./data/{SnapshotDate}/Analysis/{ID}/*.csv"
      s3: "s3://AA-AA-000-0000/data/{SnapshotDate}/Analysis/{ID}/*.parquet"
    domains:
      Analysis_Input:
        db: local
        table: "./data/{SnapshotDate}/Analysis/{ID}/Analysis_Input.csv"
      Analysis_Summary:
        db: local
        table: "./data/{SnapshotDate}/Analysis/{ID}/Analysis_Summary.csv"
  Reporting:
    db:
      local: "./data/{SnapshotDate}/Reporting/{ID}.csv"
      s3: "s3://AA-AA-000-0000/data/{SnapshotDate}/Reporting/{ID}.parquet"
    domains:
      Reporting_Results:
        db: local
        table: "./data/{SnapshotDate}/Reporting/Results.csv"
      Reporting_Metrics:
        db: local
        table: "./data/{SnapshotDate}/Reporting/Metrics.csv"
      Reporting_Groups:
        db: local
        table: "./data/{SnapshotDate}/Reporting/Groups.csv"
      Reporting_Bounds:
        db: local
        table: "./data/{SnapshotDate}/Reporting/Bounds.csv"

