- id: gsm
  repo: Gilead-BioStats/gsm
  version: dev
- id: grail
  repo: Gilead-BioStats/grail
  version: 1.0.0
- id: gsm.app
  repo: Gilead-BioStats/gsm.app
  version: 1.0.0
- id: gsm.endpoints
  repo: Gilead-BioStats/gsm.endpoints
  version: 1.0.0

