id: AA-AA-000-0000
snapshot_date: '2024-09-18'
domains:
  Raw_STUDY:
    db: clindata
    table: ctms_study
  Raw_SITE:
    db: clindata
    table: ctms_site
  Raw_SUBJ:
    db: clindata
    table: rawplus_dm
  Raw_ENROLL:
    db: clindata
    table: rawplus_enroll
  Raw_STUDCOMP:
    db: clindata
    table: rawplus_studcomp
  Raw_SDRGCOMP:
    db: clindata
    table: rawplus_sdrgcomp
  Raw_AE:
    db: clindata
    table: rawplus_ae
  Raw_LB:
    db: clindata
    table: rawplus_lb
  Raw_PD:
    db: clindata
    table: ctms_protdev
  Raw_DATAENT:
    db: clindata
    table: edc_data_pages
  Raw_DATACHG:
    db: clindata
    table: edc_data_points
  Raw_QUERY:
    db: clindata
    table: edc_queries
  Mapped_STUDY:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_STUDY.csv
  Mapped_SITE:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_SITE.csv
  Mapped_COUNTRY:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_COUNTRY.csv
  Mapped_SUBJ:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_SUBJ.csv
  Mapped_ENROLL:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_ENROLL.csv
  Mapped_STUDCOMP:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_STUDCOMP.csv
  Mapped_SDRGCOMP:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_SDRGCOMP.csv
  Mapped_AE:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_AE.csv
  Mapped_LB:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_LB.csv
  Mapped_PD:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_PD.csv
  Mapped_DATAENT:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_DATAENT.csv
  Mapped_DATACHG:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_DATACHG.csv
  Mapped_QUERY:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Mapped_QUERY.csv
  Analysis_Input:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Analysis_Input.csv
  Analysis_Summary:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Analysis_Summary.csv
  Reporting_Results:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Reporting_Results.csv
  Reporting_Metrics:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Reporting_Metrics.csv
  Reporting_Groups:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Reporting_Groups.csv
  Reporting_Bounds:
    db: local
    table: AA-AA-000-0000/data/2024-09-18/Reporting_Bounds.csv
 
 