#' Safety Assessment - Site-level plot
#'
#' @param dfFlagged Flagged data frame generated by \code{\link{AE_Poisson_Flag}}
#' @param title Title for the plot
#' @param unit exposure time unit. Defaults to "weeks".
#'
#' @return site level plot object
#'
#' @import ggplot2
#'
#' @export
AE_Visualize <- function( dfFlagged ,title = "", unit="weeks"){

  ### Calculate upper and lower boundaries
  dfBounds <- gsm::AE_Poisson_PredictBounds( dfFlagged )

  ### Plot of data
  p <- ggplot(
    dfFlagged,
    aes(x=LogExposure, y=TotalCount)
  ) +
    theme_bw(base_size=16) +
    geom_point(size=2.5, shape=19) +
    scale_x_continuous(
      breaks=log(c(5,10,50, 100, 500, 1000, 5000, 10000)),
      labels=c(5,10,50, 100, 500, 1000, 5000, 10000)
    ) +
    ggtitle( title ) +
    xlab(paste0("Site Total Exposure (",unit," - log scale)")) +
    ylab("Site Total Events") +
    geom_line( data = dfBounds, aes( x = LogExposure, y = MeanCount), color="red") +
    geom_line( data = dfBounds, aes( x = LogExposure, y = LowerCount), color="red", linetype="dashed") +
    geom_line( data = dfBounds, aes( x = LogExposure, y = UpperCount), color="red", linetype="dashed")

  # Make flagged points red and annotate site number

  vFlagDex <- which( dfFlagged$Flag != 0 )
  if( length( vFlagDex ) > 0 ){
    p<-p + geom_point(
      data = dfFlagged[ vFlagDex ,] ,
      aes( x = LogExposure, y = TotalCount ),
      col="red",
      size=2.5,
      shape=19) +
      geom_text(
        data = dfFlagged[ vFlagDex, ],
        aes( x = LogExposure, y = TotalCount, label = SiteID),
        vjust = 1.2,
        col="red",
        size=3.5
      )
  }
  return(p)
}

