on:
  pull_request:
    branches: [dev]

name: build-markdown

jobs:
  build-markdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.LOAD_CLINDATA }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Clone clindata
        run: |
          cd ..
          git clone git@github.com:Gilead-BioStats/clindata.git
          cd clindata
          cd ../gsm

      - name: install packages
        shell: Rscript {0}
        run: |
          install.packages("devtools")
          devtools::install('../clindata')
          devtools::install(dependencies=TRUE)

      - name: Build markdown
        run: gsm:::build_markdown("inst/mappings/mapping_adam.yaml")
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\*
          git commit -m "Build Markdown" || echo "No changes to commit"
          git pull --ff-only
          git push origin
