name: cache

on:
  push:
    branches: [fix-1804]
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::devtools
            any::here
            any::rcmdcheck
            any::covr
            any::xml2
          needs: website

      - name: Cache R dependencies
        uses: actions/cache@v4
        with:
          # Cache the R package library after dependencies are installed
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-
