name: testing the cache

on:
  push:
    branches: [fix-1804]
  workflow_dispatch:

jobs:
  test_w_cache:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Restore R dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: FALSE
          extra-packages: local::.

      - name: test small snippet of local pacakge code
        shell: Rscript {0}
        run: |
          lCharts <- gsm::MakeCharts(
            dfResults = gsm::reportingResults,
            dfGroups = gsm::reportingGroups,
            dfMetrics = gsm::reportingMetrics,
            dfBounds = gsm::reportingBounds
          )
          cat(names(lCharts))
          print("Is there another cache done by setup-r-dependencies for next time?")
