on:
  pull_request:
    branches: [main]
  workflow_dispatch:

name: pkgdown-main

jobs:
  pkgdown-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PKGDOWN_DEV_MODE: devel
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Generate sample reports
        shell: Rscript {0}
        run: |
          install.packages("devtools")
          devtools::install(dependencies = T)
          dir.create(here::here("pkgdown", "assets"), recursive = TRUE)

          lCharts <- gsm::MakeCharts(
            dfResults = gsm::reportingResults,
            dfGroups = gsm::reportingGroups,
            dfMetrics = gsm::reportingMetrics,
            dfBounds = gsm::reportingBounds
          )

          gsm::Report_KRI(
            lCharts = lCharts,
            dfResults =  FilterByLatestSnapshotDate(gsm::reportingResults),
            dfGroups =  gsm::reportingGroups,
            dfMetrics = gsm::reportingMetrics,
            strOutputDir = here::here("pkgdown", "assets"),
            strOutputFile = "report_kri_site.html"
          )

          ## Country Report
            lCharts_country <- gsm::MakeCharts(
            dfResults = gsm::reportingResults_country,
            dfGroups = gsm::reportingGroups_country,
            dfMetrics = gsm::reportingMetrics_country,
            dfBounds = gsm::reportingBounds_country
          )

          gsm::Report_KRI(
            lCharts = lCharts_country,
            dfResults =  gsm::FilterByLatestSnapshotDate(gsm::reportingResults_country),
            dfGroups =  gsm::reportingGroups_country,
            dfMetrics = gsm::reportingMetrics_country,
            strOutputDir = here::here("pkgdown", "assets"),
            strOutputFile = "report_kri_country.html"
          )

      - name: Deploy pkgdown
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
