on:
  push:
    branches: [fix-1804]
  workflow_dispatch:

name: pkgdown-main

jobs:
  pkgdown-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Restore R dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Generate sample reports
        shell: Rscript {0}
        run: |
          devtools::load_all()
          dir.create(here::here("pkgdown", "assets"), recursive = TRUE)

          lCharts <- MakeCharts(
            dfResults = gsm::reportingResults,
            dfGroups = gsm::reportingGroups,
            dfMetrics = gsm::reportinMetrics,
            dfBounds = gsm::reportingBounds
          )

          Report_KRI(
            lCharts = lCharts,
            dfResults =  gsm::reportingResults,
            dfGroups =  gsm::reportingGroups,
            dfMetrics = gsm::reportingMetrics,
            strOutputDir = here::here("pkgdown", "assets"),
            strOutputFile = "report_kri_site.html"
          )
